# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created: Wed Oct 31 21:51:02 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mainSplitter = QtGui.QSplitter(self.centralwidget)
        self.mainSplitter.setMinimumSize(QtCore.QSize(0, 0))
        self.mainSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.mainSplitter.setChildrenCollapsible(False)
        self.mainSplitter.setObjectName(_fromUtf8("mainSplitter"))
        self.scrollArea = QtGui.QScrollArea(self.mainSplitter)
        self.scrollArea.setMinimumSize(QtCore.QSize(200, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.areaMap = QtGui.QWidget()
        self.areaMap.setGeometry(QtCore.QRect(0, 0, 194, 541))
        self.areaMap.setObjectName(_fromUtf8("areaMap"))
        self.label = QtGui.QLabel(self.areaMap)
        self.label.setGeometry(QtCore.QRect(70, 210, 71, 41))
        self.label.setFrameShape(QtGui.QFrame.Box)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setMargin(0)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.areaMap)
        self.label_2.setGeometry(QtCore.QRect(90, 110, 71, 41))
        self.label_2.setFrameShape(QtGui.QFrame.Box)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setMargin(0)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.scrollArea.setWidget(self.areaMap)
        self.propertySplitter = QtGui.QSplitter(self.mainSplitter)
        self.propertySplitter.setOrientation(QtCore.Qt.Vertical)
        self.propertySplitter.setObjectName(_fromUtf8("propertySplitter"))
        self.hierarchyTree = QtGui.QTreeWidget(self.propertySplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hierarchyTree.sizePolicy().hasHeightForWidth())
        self.hierarchyTree.setSizePolicy(sizePolicy)
        self.hierarchyTree.setAlternatingRowColors(True)
        self.hierarchyTree.setAnimated(True)
        self.hierarchyTree.setColumnCount(2)
        self.hierarchyTree.setObjectName(_fromUtf8("hierarchyTree"))
        self.hierarchyTree.header().setDefaultSectionSize(200)
        self.propertyTable = QtGui.QTableWidget(self.propertySplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propertyTable.sizePolicy().hasHeightForWidth())
        self.propertyTable.setSizePolicy(sizePolicy)
        self.propertyTable.setAlternatingRowColors(True)
        self.propertyTable.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.propertyTable.setGridStyle(QtCore.Qt.DotLine)
        self.propertyTable.setWordWrap(False)
        self.propertyTable.setCornerButtonEnabled(False)
        self.propertyTable.setObjectName(_fromUtf8("propertyTable"))
        self.propertyTable.setColumnCount(2)
        self.propertyTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.propertyTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.propertyTable.setHorizontalHeaderItem(1, item)
        self.propertyTable.horizontalHeader().setDefaultSectionSize(120)
        self.propertyTable.horizontalHeader().setStretchLastSection(True)
        self.propertyTable.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.mainSplitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionE_xit = QtGui.QAction(MainWindow)
        self.actionE_xit.setObjectName(_fromUtf8("actionE_xit"))
        self.menu_File.addAction(self.actionNew)
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionSave_As)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionE_xit)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Armory 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Birth Springs 1", None, QtGui.QApplication.UnicodeUTF8))
        self.hierarchyTree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.hierarchyTree.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        item = self.propertyTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Property", None, QtGui.QApplication.UnicodeUTF8))
        item = self.propertyTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "&New...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionE_xit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))

